/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Class.Admin;
import Class.Employee;
import Class.Users;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AdminDashboard extends javax.swing.JFrame {
    Users user = new Users();
    Admin admin = new Admin();
    Employee empClass = new Employee();
    public AdminDashboard() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        manageUserBtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        viewEmployeeBtn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        mangePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();
        nameTxt = new javax.swing.JTextField();
        designationCombo = new javax.swing.JComboBox<>();
        updateBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        emp = new javax.swing.JPanel();
        searchCombo = new javax.swing.JComboBox<>();
        searchTxt = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        empSearchtable = new javax.swing.JTable();
        searchBtn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        allBtn = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab1", jPanel3);

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(820, 650));
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dashboard");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        manageUserBtn.setBackground(new java.awt.Color(102, 102, 102));
        manageUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageUserBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageUserBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageUserBtnMouseExited(evt);
            }
        });
        manageUserBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Manage User");
        manageUserBtn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        jPanel1.add(manageUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 179, 143, 60));

        viewEmployeeBtn.setBackground(new java.awt.Color(102, 102, 102));
        viewEmployeeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewEmployeeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewEmployeeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewEmployeeBtnMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("View Employee");

        javax.swing.GroupLayout viewEmployeeBtnLayout = new javax.swing.GroupLayout(viewEmployeeBtn);
        viewEmployeeBtn.setLayout(viewEmployeeBtnLayout);
        viewEmployeeBtnLayout.setHorizontalGroup(
            viewEmployeeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewEmployeeBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        viewEmployeeBtnLayout.setVerticalGroup(
            viewEmployeeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewEmployeeBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(viewEmployeeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 143, -1));

        mangePanel.setBackground(new java.awt.Color(102, 102, 102));
        mangePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "passwordl", "username", "Designation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.setRowHeight(25);
        userTable.setRowMargin(5);
        userTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        mangePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 627, 250));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("User Name");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 72, 90, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Name");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 50, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Designation");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, 30));
        jPanel5.add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 230, 30));
        jPanel5.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 230, 30));
        jPanel5.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 230, 30));

        designationCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Destination", "Hr Manager", "Hr Assitance" }));
        jPanel5.add(designationCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 230, 30));

        updateBtn.setBackground(new java.awt.Color(51, 51, 51));
        updateBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setToolTipText("");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBtnMouseExited(evt);
            }
        });
        updateBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Update");
        updateBtn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 40));

        jPanel5.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 130, 30));

        saveBtn.setBackground(new java.awt.Color(51, 51, 51));
        saveBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 1, true));
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveBtnMouseExited(evt);
            }
        });
        saveBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Save");
        saveBtn.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 110, 30));

        jPanel5.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Add User");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        mangePanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 620, 200));

        deleteBtn.setBackground(new java.awt.Color(102, 102, 102));
        deleteBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBtnMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Delete");

        javax.swing.GroupLayout deleteBtnLayout = new javax.swing.GroupLayout(deleteBtn);
        deleteBtn.setLayout(deleteBtnLayout);
        deleteBtnLayout.setHorizontalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );
        deleteBtnLayout.setVerticalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        mangePanel.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin");

        emp.setBackground(new java.awt.Color(102, 102, 102));
        emp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee Id", "Employee Name", "EPF no", "Nic", "Department", "Designation", "Salary" }));
        emp.add(searchCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 30));
        emp.add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 290, 30));

        empSearchtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmpID", "Name", "EPF no", "Nic", "Date of Join", "Department", "Designation", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(empSearchtable);

        emp.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 630, 420));

        searchBtn.setBackground(new java.awt.Color(102, 102, 102));
        searchBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 2));
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBtnMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Search");

        javax.swing.GroupLayout searchBtnLayout = new javax.swing.GroupLayout(searchBtn);
        searchBtn.setLayout(searchBtnLayout);
        searchBtnLayout.setHorizontalGroup(
            searchBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );
        searchBtnLayout.setVerticalGroup(
            searchBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        emp.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 60, 30));

        allBtn.setBackground(new java.awt.Color(102, 102, 102));
        allBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        allBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                allBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                allBtnMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("All");

        javax.swing.GroupLayout allBtnLayout = new javax.swing.GroupLayout(allBtn);
        allBtn.setLayout(allBtnLayout);
        allBtnLayout.setHorizontalGroup(
            allBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );
        allBtnLayout.setVerticalGroup(
            allBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        emp.add(allBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 60, 30));

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(202, 202, 202)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(154, Short.MAX_VALUE)
                    .addComponent(emp, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(43, Short.MAX_VALUE)
                    .addComponent(emp, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Hover - mouse Enter
    private void manageUserBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserBtnMouseEntered
        manageUserBtn.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_manageUserBtnMouseEntered

    private void viewEmployeeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEmployeeBtnMouseEntered
        viewEmployeeBtn.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_viewEmployeeBtnMouseEntered
    //Window Open Functions
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        for (int i=1;i<user.rowCount();i++){
             String[] dataRow = user.users()[i];
             model.addRow(dataRow);
        }
        
        DefaultTableModel model1 = (DefaultTableModel) empSearchtable.getModel();
        for (int i=0;i<empClass.rowsEmp();i++){
             String[] dataRow = empClass.showEmployee()[i];
             model1.addRow(dataRow);
        }
        mangePanel.setVisible(true);
        emp.setVisible(false);
    }//GEN-LAST:event_formWindowOpened
    //hover
    private void manageUserBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserBtnMouseExited
        manageUserBtn.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_manageUserBtnMouseExited

    private void viewEmployeeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEmployeeBtnMouseExited
        viewEmployeeBtn.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_viewEmployeeBtnMouseExited

    private void saveBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseEntered
        saveBtn.setBackground(new Color(0,253,0));
    }//GEN-LAST:event_saveBtnMouseEntered

    private void saveBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseExited
        saveBtn.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_saveBtnMouseExited

    private void updateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseEntered
        updateBtn.setBackground(new Color(255,255,51));
    }//GEN-LAST:event_updateBtnMouseEntered

    private void updateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseExited
        updateBtn.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_updateBtnMouseExited

    private void deleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseEntered
        deleteBtn.setBackground(Color.RED);
    }//GEN-LAST:event_deleteBtnMouseEntered

    private void deleteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseExited
        deleteBtn.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_deleteBtnMouseExited
    // Save Button Function
    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        
        String passwordString = new String(passwordTxt.getPassword());
        if (userNameTxt.getText().isEmpty()||passwordString.isEmpty()||nameTxt.getText().isEmpty()||designationCombo.getSelectedItem().equals("Select Destination")){
            JOptionPane.showMessageDialog(rootPane,"All field Required!!","Error", JOptionPane.ERROR_MESSAGE);
        } else if(admin.creteUserAccounts(userNameTxt.getText(), passwordString, nameTxt.getText(), designationCombo.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(rootPane,"Create Account Successfully","Succuessful", JOptionPane.OK_OPTION);
            showTable();
            clrAddUser();
        }else{
            JOptionPane.showMessageDialog(rootPane,"This User Name Already Assigend!!","Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_saveBtnMouseClicked
    //Delete Functions
    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        
        if (userTable.getSelectedRowCount()==0){
             
            JOptionPane.showMessageDialog(rootPane,"Select Row First!","Error", JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            int results = JOptionPane.showConfirmDialog(rootPane,"Do you want to Delete?","Conformation",JOptionPane.OK_CANCEL_OPTION);
            if (results==JOptionPane.OK_OPTION){
                admin.userDelete(userTable.getSelectedRow()+1);
                showTable();
                clrAddUser();
            }
            
        }
        
    }//GEN-LAST:event_deleteBtnMouseClicked
    //Table Click and get data
    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        clrAddUser();
        Users user = new Users();
        int select = userTable.getSelectedRow()+1;
        userNameTxt.setText(user.users()[select][0]);
        passwordTxt.setText("");
        nameTxt.setText(user.users()[select][2]);
        designationCombo.setSelectedItem(user.users()[select][3]);
        
    }//GEN-LAST:event_userTableMouseClicked
    //Update mouse btn
    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        String passwordString = new String(passwordTxt.getPassword());
        if (userTable.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(rootPane,"Select Row First!","Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int results = JOptionPane.showConfirmDialog(rootPane,"Do you want to Delete?","Conformation",JOptionPane.OK_CANCEL_OPTION);
            if (results==JOptionPane.OK_OPTION){
                admin.userEdit(userTable.getSelectedRow()+1, userNameTxt.getText(), passwordString, nameTxt.getText() , designationCombo.getSelectedItem().toString());
                showTable();
                clrAddUser();
            }
            
        }
    }//GEN-LAST:event_updateBtnMouseClicked

    private void manageUserBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserBtnMouseClicked
        mangePanel.setVisible(true);
        emp.setVisible(false);
    }//GEN-LAST:event_manageUserBtnMouseClicked

    private void viewEmployeeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEmployeeBtnMouseClicked
        mangePanel.setVisible(false);
        emp.setVisible(true);
    }//GEN-LAST:event_viewEmployeeBtnMouseClicked

    private void searchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseEntered
        searchBtn.setBackground(new Color(0,255,0));
    }//GEN-LAST:event_searchBtnMouseEntered

    private void allBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allBtnMouseEntered
        allBtn.setBackground(new Color(255,255,0));
    }//GEN-LAST:event_allBtnMouseEntered

    private void searchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseExited
        searchBtn.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_searchBtnMouseExited

    private void allBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allBtnMouseExited
        allBtn.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_allBtnMouseExited

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        int searchBy;
        int index = searchCombo.getSelectedIndex();
        
        switch (index) {
            case 0:
                searchBy=0;
                break;
            case 1:
                searchBy =1;
                break;
            case 2:
                searchBy = 2;
                break;
            case 3:
                searchBy = 3;
                break;
            case 4:
                searchBy = 5;
                break;
            case 5:
                searchBy = 6;
                break;
            case 6:
                searchBy = 7;
                break;
            default:
                searchBy = 0;
        }
        
        
        DefaultTableModel model = (DefaultTableModel) empSearchtable.getModel();
        int rowsTable = model.getRowCount();
        for (int i = rowsTable-1;i>=0;i--){
            model.removeRow(i);
        }
        
        if (empClass.searchEmp(searchBy, searchTxt.getText()).length==0) {
            JOptionPane.showMessageDialog(rootPane,"No record found","Error", JOptionPane.ERROR_MESSAGE);
        } else {
            for (int i=0;i<empClass.searchEmp(searchBy, searchTxt.getText()).length;i++){
                String[] dataRow =empClass.searchEmp(searchBy, searchTxt.getText())[i];
                model.addRow(dataRow);
            }
        }
    }//GEN-LAST:event_searchBtnMouseClicked

    private void allBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) empSearchtable.getModel();
        int rowsTable = model.getRowCount();
        for (int i = rowsTable-1;i>=0;i--){
            model.removeRow(i);
        }
        for (int i=0;i<empClass.rowsEmp();i++){
             String[] dataRow = empClass.showEmployee()[i];
             model.addRow(dataRow);
        }
    }//GEN-LAST:event_allBtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login logout = new Login();
        logout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    //Show Table
    private void showTable(){
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        int rowsTable = model.getRowCount();
        for (int i = rowsTable-1;i>=0;i--){
            model.removeRow(i);
        }
        for (int i=1;i<user.rowCount();i++){
             String[] dataRow = user.users()[i];
             model.addRow(dataRow);
        }
    }
    //Clear user
    private void clrAddUser(){
        userNameTxt.setText("");
        passwordTxt.setText("");
        nameTxt.setText("");
        designationCombo.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allBtn;
    private javax.swing.JPanel deleteBtn;
    private javax.swing.JComboBox<String> designationCombo;
    private javax.swing.JPanel emp;
    private javax.swing.JTable empSearchtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel manageUserBtn;
    private javax.swing.JPanel mangePanel;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JPanel saveBtn;
    private javax.swing.JPanel searchBtn;
    private javax.swing.JComboBox<String> searchCombo;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JPanel updateBtn;
    private javax.swing.JTextField userNameTxt;
    private javax.swing.JTable userTable;
    private javax.swing.JPanel viewEmployeeBtn;
    // End of variables declaration//GEN-END:variables
}
