
package Ui;

import Class.Department;
import Class.Designation;
import Class.Employee;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class HrManagerDashboard extends javax.swing.JFrame {

    Department dept = new Department();
    Designation dest = new Designation();
    Employee emp = new Employee();
    
    public HrManagerDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        deptBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DesigBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addEmpBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mainFrame = new javax.swing.JPanel();
        deptpanel = new javax.swing.JPanel();
        deptNameTxt = new javax.swing.JTextField();
        departmentAddbtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        departmentTable = new javax.swing.JTable();
        destPanel = new javax.swing.JPanel();
        addDestBtn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        destNameTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        destTable = new javax.swing.JTable();
        empPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        empIdTxt = new javax.swing.JTextField();
        empNameTxt = new javax.swing.JTextField();
        empEpfTxt = new javax.swing.JTextField();
        empNicTxt = new javax.swing.JTextField();
        empDojTxt = new javax.swing.JTextField();
        deptCombo = new javax.swing.JComboBox<>();
        DestCombo = new javax.swing.JComboBox<>();
        empSalrytxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        empSaveBtn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        empClsBtn = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchBy = new javax.swing.JComboBox<>();
        searchTxt = new javax.swing.JTextField();
        searchButton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        allBtn = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        empSearchtable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Dashboard");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        deptBtn.setBackground(new java.awt.Color(51, 51, 51));
        deptBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deptBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deptBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deptBtnMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Departments");

        javax.swing.GroupLayout deptBtnLayout = new javax.swing.GroupLayout(deptBtn);
        deptBtn.setLayout(deptBtnLayout);
        deptBtnLayout.setHorizontalGroup(
            deptBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deptBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deptBtnLayout.setVerticalGroup(
            deptBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deptBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DesigBtn.setBackground(new java.awt.Color(51, 51, 51));
        DesigBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesigBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DesigBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DesigBtnMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Designation");

        javax.swing.GroupLayout DesigBtnLayout = new javax.swing.GroupLayout(DesigBtn);
        DesigBtn.setLayout(DesigBtnLayout);
        DesigBtnLayout.setHorizontalGroup(
            DesigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesigBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        DesigBtnLayout.setVerticalGroup(
            DesigBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesigBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addEmpBtn.setBackground(new java.awt.Color(51, 51, 51));
        addEmpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmpBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addEmpBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addEmpBtnMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee");

        javax.swing.GroupLayout addEmpBtnLayout = new javax.swing.GroupLayout(addEmpBtn);
        addEmpBtn.setLayout(addEmpBtnLayout);
        addEmpBtnLayout.setHorizontalGroup(
            addEmpBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmpBtnLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addEmpBtnLayout.setVerticalGroup(
            addEmpBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmpBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchBtn.setBackground(new java.awt.Color(51, 51, 51));
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBtnMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");

        javax.swing.GroupLayout searchBtnLayout = new javax.swing.GroupLayout(searchBtn);
        searchBtn.setLayout(searchBtnLayout);
        searchBtnLayout.setHorizontalGroup(
            searchBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        searchBtnLayout.setVerticalGroup(
            searchBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deptBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DesigBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addEmpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(deptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DesigBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 580));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dashboard");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setText("log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 730, 50));

        mainFrame.setBackground(new java.awt.Color(51, 51, 51));
        mainFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deptpanel.setBackground(new java.awt.Color(51, 51, 51));
        deptpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deptNameTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deptNameTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        deptNameTxt.setBorder(null);
        deptpanel.add(deptNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 210, 50));

        departmentAddbtn.setBackground(new java.awt.Color(51, 51, 51));
        departmentAddbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), null));
        departmentAddbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departmentAddbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                departmentAddbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                departmentAddbtnMouseExited(evt);
            }
        });
        departmentAddbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Department");
        departmentAddbtn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        deptpanel.add(departmentAddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 210, 40));

        departmentTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        departmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Departments"
            }
        ));
        jScrollPane1.setViewportView(departmentTable);

        deptpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 280, -1));

        mainFrame.add(deptpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        destPanel.setBackground(new java.awt.Color(51, 51, 51));
        destPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addDestBtn.setBackground(new java.awt.Color(51, 51, 51));
        addDestBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), null));
        addDestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDestBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addDestBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addDestBtnMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setLabelFor(addDestBtn);
        jLabel8.setText("Add Designation");

        javax.swing.GroupLayout addDestBtnLayout = new javax.swing.GroupLayout(addDestBtn);
        addDestBtn.setLayout(addDestBtnLayout);
        addDestBtnLayout.setHorizontalGroup(
            addDestBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        addDestBtnLayout.setVerticalGroup(
            addDestBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        destPanel.add(addDestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 170, 40));

        destNameTxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        destNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        destPanel.add(destNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 170, 40));

        destTable.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        destTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Designation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        destTable.setRowHeight(25);
        destTable.setRowMargin(5);
        jScrollPane2.setViewportView(destTable);

        destPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 50, 260, 400));

        mainFrame.add(destPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        empPanel.setBackground(new java.awt.Color(51, 51, 51));
        empPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmpID", "Name", "EPF no", "Nic", "Date of Join", "Department", "Designation", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(empTable);
        if (empTable.getColumnModel().getColumnCount() > 0) {
            empTable.getColumnModel().getColumn(1).setResizable(false);
        }

        empPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 680, 180));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(empIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 120, 30));
        jPanel4.add(empNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 180, 30));
        jPanel4.add(empEpfTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 180, 30));
        jPanel4.add(empNicTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 180, 30));
        jPanel4.add(empDojTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 140, 30));

        deptCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department" }));
        jPanel4.add(deptCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 170, 30));

        DestCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Destination" }));
        jPanel4.add(DestCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 170, 30));
        jPanel4.add(empSalrytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 150, 30));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Emp ID");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Name");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("EPF no.");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("NIC");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Date of Join");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Department");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Designation");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Salary");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        empSaveBtn.setBackground(new java.awt.Color(51, 51, 51));
        empSaveBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), null));
        empSaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empSaveBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empSaveBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empSaveBtnMouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Save");

        javax.swing.GroupLayout empSaveBtnLayout = new javax.swing.GroupLayout(empSaveBtn);
        empSaveBtn.setLayout(empSaveBtnLayout);
        empSaveBtnLayout.setHorizontalGroup(
            empSaveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empSaveBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
        );
        empSaveBtnLayout.setVerticalGroup(
            empSaveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empSaveBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(empSaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, 30));

        empClsBtn.setBackground(new java.awt.Color(51, 51, 51));
        empClsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empClsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empClsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empClsBtnMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Clear");

        javax.swing.GroupLayout empClsBtnLayout = new javax.swing.GroupLayout(empClsBtn);
        empClsBtn.setLayout(empClsBtnLayout);
        empClsBtnLayout.setHorizontalGroup(
            empClsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empClsBtnLayout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        empClsBtnLayout.setVerticalGroup(
            empClsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel4.add(empClsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, 30));

        empPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 690, 260));

        deleteBtn.setBackground(new java.awt.Color(51, 51, 51));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBtnMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Delete");

        javax.swing.GroupLayout deleteBtnLayout = new javax.swing.GroupLayout(deleteBtn);
        deleteBtn.setLayout(deleteBtnLayout);
        deleteBtnLayout.setHorizontalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );
        deleteBtnLayout.setVerticalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20))
        );

        empPanel.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, 20));

        mainFrame.add(empPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        searchPanel.setBackground(new java.awt.Color(51, 51, 51));

        searchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee Id", "Employee Name", "EPF no", "Nic", "Department", "Designation", "Salary" }));

        searchButton.setBackground(new java.awt.Color(51, 51, 51));
        searchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), null));
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchButtonMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Search");

        javax.swing.GroupLayout searchButtonLayout = new javax.swing.GroupLayout(searchButton);
        searchButton.setLayout(searchButtonLayout);
        searchButtonLayout.setHorizontalGroup(
            searchButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        searchButtonLayout.setVerticalGroup(
            searchButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        allBtn.setBackground(new java.awt.Color(51, 51, 51));
        allBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), null));
        allBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                allBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                allBtnMouseExited(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Show ALL");

        javax.swing.GroupLayout allBtnLayout = new javax.swing.GroupLayout(allBtn);
        allBtn.setLayout(allBtnLayout);
        allBtnLayout.setHorizontalGroup(
            allBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        allBtnLayout.setVerticalGroup(
            allBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        empSearchtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmpID", "Name", "EPF no", "Nic", "Date of Join", "Department", "Designation", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(empSearchtable);
        if (empSearchtable.getColumnModel().getColumnCount() > 0) {
            empSearchtable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBy, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(searchTxt)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainFrame.add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        jPanel1.add(mainFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 710, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void enterMouse(JPanel pl){
        pl.setBackground(new Color(255,102,0));  
    }
    private void exitMouse(JPanel pl){
        pl.setBackground(new Color(51,51,51));  
    }
    
    //hover Effect
    private void deptBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deptBtnMouseEntered
        enterMouse(deptBtn);
    }//GEN-LAST:event_deptBtnMouseEntered

    private void deptBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deptBtnMouseExited
        exitMouse(deptBtn);
    }//GEN-LAST:event_deptBtnMouseExited

    private void DesigBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesigBtnMouseEntered
        enterMouse(DesigBtn);
    }//GEN-LAST:event_DesigBtnMouseEntered

    private void DesigBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesigBtnMouseExited
        exitMouse(DesigBtn);
    }//GEN-LAST:event_DesigBtnMouseExited

    private void addEmpBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmpBtnMouseEntered
        enterMouse(addEmpBtn);
    }//GEN-LAST:event_addEmpBtnMouseEntered

    private void addEmpBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmpBtnMouseExited
        exitMouse(addEmpBtn);
    }//GEN-LAST:event_addEmpBtnMouseExited

    private void searchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseEntered
        enterMouse(searchBtn);
    }//GEN-LAST:event_searchBtnMouseEntered

    private void searchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseExited
        exitMouse(searchBtn);
    }//GEN-LAST:event_searchBtnMouseExited

    private void departmentAddbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentAddbtnMouseEntered
        enterMouse(departmentAddbtn);
    }//GEN-LAST:event_departmentAddbtnMouseEntered

    private void departmentAddbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentAddbtnMouseExited
        exitMouse(departmentAddbtn);
    }//GEN-LAST:event_departmentAddbtnMouseExited
    //Department Add
    private void departmentAddbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentAddbtnMouseClicked
        if (deptNameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Department Name Required!!","Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(dept.createDepartment(deptNameTxt.getText())){
            JOptionPane.showMessageDialog(rootPane,"Department add Successfully","Succuessful", JOptionPane.OK_OPTION);
            showDeptTable();
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Department Name Already Added!!","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_departmentAddbtnMouseClicked
    //when opening windows
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showDeptTable();
        showDestTable();
        showEmpSearchTable();
        showEmpTable();
        AddComboBox();
        
        deptpanel.setVisible(true);
        destPanel.setVisible(false);
        empPanel.setVisible(false);
        searchPanel.setVisible(false);
    }//GEN-LAST:event_formWindowOpened
    //hover
    private void addDestBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDestBtnMouseEntered
        enterMouse(addDestBtn);
    }//GEN-LAST:event_addDestBtnMouseEntered

    private void addDestBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDestBtnMouseExited
        exitMouse(addDestBtn);
    }//GEN-LAST:event_addDestBtnMouseExited
    //Add Designation
    private void addDestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDestBtnMouseClicked
        if (destNameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Desigantion Name Required!!","Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(dest.createDesignation(destNameTxt.getText())){
            JOptionPane.showMessageDialog(rootPane,"Desigantion add Successfully","Succuessful", JOptionPane.OK_OPTION);
            showDestTable();
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Desigantion Name Already Added!!","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addDestBtnMouseClicked
    //hover
    private void empSaveBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empSaveBtnMouseEntered
        empSaveBtn.setBackground(new Color(0,255,0));
    }//GEN-LAST:event_empSaveBtnMouseEntered

    private void empClsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empClsBtnMouseEntered
        empClsBtn.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_empClsBtnMouseEntered

    private void deleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseEntered
        deleteBtn.setBackground(Color.RED);
    }//GEN-LAST:event_deleteBtnMouseEntered

    private void empSaveBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empSaveBtnMouseExited
        empSaveBtn.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_empSaveBtnMouseExited

    private void empClsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empClsBtnMouseExited
       empClsBtn.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_empClsBtnMouseExited

    private void deleteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseExited
        deleteBtn.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_deleteBtnMouseExited
    //employee Save Button
    private void empSaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empSaveBtnMouseClicked
        if (empEpfTxt.getText().isEmpty()||empNameTxt.getText().isEmpty()||empNicTxt.getText().isEmpty()||empDojTxt.getText().isEmpty()||empSalrytxt.getText().isEmpty()||deptCombo.getSelectedIndex()==0||DestCombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane,"All field Required!!","Error", JOptionPane.ERROR_MESSAGE);
        }else{
            emp.setEmpDetails(empIdTxt.getText(), empNameTxt.getText(), empEpfTxt.getText(), empNicTxt.getText(), empDojTxt.getText(), deptCombo.getSelectedItem().toString(), DestCombo.getSelectedItem().toString(), empSalrytxt.getText());
            emp.createEmployee();
            showEmpTable();
            clearEmpTxt();
        }
    }//GEN-LAST:event_empSaveBtnMouseClicked

    private void deptBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deptBtnMouseClicked
        deptpanel.setVisible(true);
        destPanel.setVisible(false);
        empPanel.setVisible(false);
        searchPanel.setVisible(false);
    }//GEN-LAST:event_deptBtnMouseClicked

    private void DesigBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesigBtnMouseClicked
        deptpanel.setVisible(false);
        destPanel.setVisible(true);
        empPanel.setVisible(false);
        searchPanel.setVisible(false);
    }//GEN-LAST:event_DesigBtnMouseClicked

    private void addEmpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmpBtnMouseClicked
        deptpanel.setVisible(false);
        destPanel.setVisible(false);
        empPanel.setVisible(true);
        searchPanel.setVisible(false);
        AddComboBox();
    }//GEN-LAST:event_addEmpBtnMouseClicked

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        deptpanel.setVisible(false);
        destPanel.setVisible(false);
        empPanel.setVisible(false);
        searchPanel.setVisible(true);
        showEmpSearchTable();
    }//GEN-LAST:event_searchBtnMouseClicked

    private void searchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonMouseEntered

    private void allBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_allBtnMouseExited

    private void allBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_allBtnMouseEntered

    private void searchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonMouseExited

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonMouseClicked

    private void allBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allBtnMouseClicked
        /*int searchBy;
        int index = searchBy.getSelectedIndex();
        
        switch (index) {
            case 0:
                searchBy=0;
                break;
            case 1:
                searchBy =1;
                break;
            case 2:
                searchBy = 2;
                break;
            case 3:
                searchBy = 3;
                break;
            case 4:
                searchBy = 5;
                break;
            case 5:
                searchBy = 6;
                break;
            case 6:
                searchBy = 7;
                break;
            default:
                searchBy = 0;
        }
        
        
        DefaultTableModel model = (DefaultTableModel) empSearchtable.getModel();
        int rowsTable = model.getRowCount();
        for (int i = rowsTable-1;i>=0;i--){
            model.removeRow(i);
        }
        
        if (emp.searchEmp(searchBy, searchTxt.getText()).length==0) {
            JOptionPane.showMessageDialog(rootPane,"No record found","Error", JOptionPane.ERROR_MESSAGE);
        } else {
            for (int i=0;i<emp.searchEmp(searchBy, searchTxt.getText()).length;i++){
                String[] dataRow =emp.searchEmp(searchBy, searchTxt.getText())[i];
                model.addRow(dataRow);
            }
        }*/
    }//GEN-LAST:event_allBtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login logout = new Login();
        logout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void empClsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empClsBtnMouseClicked
        clearEmpTxt();
    }//GEN-LAST:event_empClsBtnMouseClicked
    //Combo Box
    public void AddComboBox(){
        deptCombo.removeAllItems();
        DestCombo.removeAllItems();
        
        deptCombo.addItem("Select Department");
        DestCombo.addItem("Select Destination");
        for (int i=0;i<dept.rowDept();i++){
             String depatments = dept.viewDepartment()[i];
             deptCombo.addItem(depatments);
        }
        for (int i=0;i<dest.rowDest();i++){
             String destinations = dest.viewDesignation()[i];
             DestCombo.addItem(destinations);
        }
    }
    //Tables Showing
    public void showDeptTable(){
        DefaultTableModel model = (DefaultTableModel) departmentTable.getModel();
        int rowsTable = model.getRowCount();
        for (int i = rowsTable-1;i>=0;i--){
            model.removeRow(i);
        }
        for (int i=0;i<dept.rowDept();i++){
             String dataRow = dept.viewDepartment()[i];
             model.addRow(new Object[]{dataRow});
        }
    }
    public void showDestTable(){
        DefaultTableModel model = (DefaultTableModel) destTable.getModel();
        int rowsTable = model.getRowCount();
        for (int i = rowsTable-1;i>=0;i--){
            model.removeRow(i);
        }
        for (int i=0;i<dest.rowDest();i++){
             String dataRow = dest.viewDesignation()[i];
             model.addRow(new Object[]{dataRow});
        }
    }
    
    public void showEmpSearchTable(){
        DefaultTableModel model = (DefaultTableModel) empSearchtable.getModel();
        int rowsTable = model.getRowCount();
        for (int i = rowsTable-1;i>=0;i--){
            model.removeRow(i);
        }
        for (int i=0;i<emp.rowsEmp();i++){
             String[] dataRow = emp.showEmployee()[i];
             model.addRow(dataRow);
        }
        
    }
    public void showEmpTable(){
        DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        int rowsTable = model.getRowCount();
        for (int i = rowsTable-1;i>=0;i--){
            model.removeRow(i);
        }
        for (int i=0;i<emp.rowsEmp();i++){
             String[] dataRow = emp.showEmployee()[i];
             model.addRow(dataRow);
        }
    }
    public void clearEmpTxt(){
           empIdTxt.setText("");
           empNameTxt.setText("");
           empEpfTxt.setText("");
           empDojTxt.setText("");
           empNicTxt.setText("");
           empSalrytxt.setText("");
           DestCombo.setSelectedIndex(0);
           deptCombo.setSelectedIndex(0);
       }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrManagerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DesigBtn;
    private javax.swing.JComboBox<String> DestCombo;
    private javax.swing.JPanel addDestBtn;
    private javax.swing.JPanel addEmpBtn;
    private javax.swing.JPanel allBtn;
    private javax.swing.JPanel deleteBtn;
    private javax.swing.JPanel departmentAddbtn;
    private javax.swing.JTable departmentTable;
    private javax.swing.JPanel deptBtn;
    private javax.swing.JComboBox<String> deptCombo;
    private javax.swing.JTextField deptNameTxt;
    private javax.swing.JPanel deptpanel;
    private javax.swing.JTextField destNameTxt;
    private javax.swing.JPanel destPanel;
    private javax.swing.JTable destTable;
    private javax.swing.JPanel empClsBtn;
    private javax.swing.JTextField empDojTxt;
    private javax.swing.JTextField empEpfTxt;
    private javax.swing.JTextField empIdTxt;
    private javax.swing.JTextField empNameTxt;
    private javax.swing.JTextField empNicTxt;
    private javax.swing.JPanel empPanel;
    private javax.swing.JTextField empSalrytxt;
    private javax.swing.JPanel empSaveBtn;
    private javax.swing.JTable empSearchtable;
    private javax.swing.JTable empTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JPanel searchBtn;
    private javax.swing.JPanel searchButton;
    private javax.swing.JComboBox<String> searchBy;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTxt;
    // End of variables declaration//GEN-END:variables
}
